# Generated by Django 3.2.1 on 2021-05-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210516_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
