# Generated by Django 3.2.1 on 2021-05-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_infouser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
