# Generated by Django 3.2.1 on 2021-05-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_user'),
        ('customer', '0005_infouser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocial',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.card'),
        ),
    ]
