# Generated by Django 3.2.1 on 2021-05-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_usersocial_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='sub_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
