# Generated by Django 3.2.1 on 2021-05-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_infouser_sub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocial',
            name='url_social',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
