# Generated by Django 3.2.3 on 2021-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_usersocial_url_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage='statics/media/avatars', upload_to=''),
        ),
    ]
