# Generated by Django 3.2.3 on 2021-06-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_infouser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
