# Generated by Django 3.2.3 on 2021-06-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_usersocial_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocial',
            name='url_scheme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='url_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
