# Generated by Django 3.2.3 on 2021-06-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20210604_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='avatar',
            field=models.ImageField(blank=True, default='statics/media/avatars/avatar5.jpeg', null=True, upload_to=''),
        ),
    ]
