# Generated by Django 3.2.1 on 2021-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
