# Generated by Django 3.2.1 on 2021-05-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_social_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
